### ISSUE TITLE
A request to add the bot to the ULTRAKILL game subreddit

### ISSUE THREAD

**Issue by KoggaJ** [Zylvian/RedditWikiaBot#1]
**Subreddit link:**
https://www.reddit.com/r/Ultrakill/

**fandom.wiki link:**
https://ultrakill.fandom.com/wiki/Home

**Comment by Zylvian** [comment]
Heyo chief.

Bot is currently not being hosted, unfortunately. Will let you know if that changes!

Furthermore, might I ask how you found this repo?

**Comment by KoggaJ** [comment]
I googled "Reddit fandom wiki bot" and your github popped up. I saw it being used on some anime subs, so I assumed it's still active
